
name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "Incomplete"]
assignees: []

body:
 - type: markdown
   attributes:
    value: "## Check List:"
 - type: checkboxes
   attributes:
    label: "I Have checked the [issues](https://github.com/InsideAgent/InsideAgentBot/issues) for duplicates."
