
name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "Incomplete"]
assignees: []

body:
 - type: checkboxes
   id: bug-reqs
   attributes:
    label: "# Bug Report Check List"
    description: Please read all options thoroughly.
    options:
      - label: "I have searched the [issues](https://github.com/InsideAgent/InsideAgentBot/issues) page for duplicates."
        required: true
      - label: "**Black cat**"
